-- =====================================================================
-- Dating Platform - initial schema
--
-- Conventions
--   * UUID primary keys, generated by the application (Hibernate).
--   * Every aggregate carries created_at / updated_at / created_by /
--     updated_by / version, matching BaseEntity. Pure join tables do not.
--   * Timestamps are TIMESTAMPTZ. The application works exclusively in UTC.
--   * Foreign keys are named explicitly so failures are readable in logs.
--   * Indexes exist for the access paths the services actually use; each
--     one is justified by a query, not added speculatively.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id                         UUID PRIMARY KEY,
    email                      VARCHAR(180)  NOT NULL,
    password_hash              VARCHAR(100)  NOT NULL,
    display_name               VARCHAR(60)   NOT NULL,
    date_of_birth              DATE          NOT NULL,
    gender                     VARCHAR(20)   NOT NULL,
    status                     VARCHAR(30)   NOT NULL,
    latitude                   DOUBLE PRECISION,
    longitude                  DOUBLE PRECISION,
    city                       VARCHAR(120),
    country                    VARCHAR(2),
    preferred_min_age          INTEGER       NOT NULL DEFAULT 18,
    preferred_max_age          INTEGER       NOT NULL DEFAULT 45,
    preferred_max_distance_km  INTEGER       NOT NULL DEFAULT 80,
    global_mode                BOOLEAN       NOT NULL DEFAULT FALSE,
    photo_verified             BOOLEAN       NOT NULL DEFAULT FALSE,
    email_verified             BOOLEAN       NOT NULL DEFAULT FALSE,
    incognito                  BOOLEAN       NOT NULL DEFAULT FALSE,
    last_active_at             TIMESTAMPTZ,
    onboarding_completed_at    TIMESTAMPTZ,
    created_at                 TIMESTAMPTZ   NOT NULL,
    updated_at                 TIMESTAMPTZ   NOT NULL,
    created_by                 UUID,
    updated_by                 UUID,
    version                    BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_age_range CHECK (preferred_min_age <= preferred_max_age)
);

CREATE INDEX idx_users_status       ON users (status);
CREATE INDEX idx_users_location     ON users (latitude, longitude);
CREATE INDEX idx_users_last_active  ON users (last_active_at);
-- Supports the discovery candidate scan, which always filters on status + dob.
CREATE INDEX idx_users_discovery    ON users (status, date_of_birth) WHERE onboarding_completed_at IS NOT NULL;

CREATE TABLE user_roles (
    user_id UUID        NOT NULL,
    role    VARCHAR(20) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_user_roles_user ON user_roles (user_id);

CREATE TABLE user_interested_in (
    user_id UUID        NOT NULL,
    gender  VARCHAR(20) NOT NULL,
    CONSTRAINT fk_user_interested_in_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_user_interested_in_user ON user_interested_in (user_id);
-- The discovery query probes this table by (user_id, gender) in an EXISTS clause.
CREATE INDEX idx_user_interested_in_lookup ON user_interested_in (gender, user_id);

CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL,
    family_id   UUID         NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at  TIMESTAMPTZ,
    user_agent  VARCHAR(250),
    ip_address  VARCHAR(60),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_refresh_tokens_user   ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id);

-- ---------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------
CREATE TABLE interests (
    id         UUID PRIMARY KEY,
    slug       VARCHAR(60) NOT NULL,
    label      VARCHAR(60) NOT NULL,
    category   VARCHAR(40) NOT NULL,
    emoji      VARCHAR(8),
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by UUID,
    updated_by UUID,
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_interests_slug UNIQUE (slug)
);

CREATE TABLE qualities (
    id              UUID PRIMARY KEY,
    slug            VARCHAR(60)      NOT NULL,
    label           VARCHAR(60)      NOT NULL,
    dimension       VARCHAR(40)      NOT NULL,
    affinity_weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    active          BOOLEAN          NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ      NOT NULL,
    updated_at      TIMESTAMPTZ      NOT NULL,
    created_by      UUID,
    updated_by      UUID,
    version         BIGINT           NOT NULL DEFAULT 0,
    CONSTRAINT uk_qualities_slug UNIQUE (slug),
    CONSTRAINT ck_qualities_affinity CHECK (affinity_weight BETWEEN -1.0 AND 1.0)
);

CREATE TABLE prompts (
    id            UUID PRIMARY KEY,
    slug          VARCHAR(80)  NOT NULL,
    text          VARCHAR(160) NOT NULL,
    category      VARCHAR(40)  NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    UUID,
    updated_by    UUID,
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_prompts_slug UNIQUE (slug)
);

-- ---------------------------------------------------------------------
-- Profiles
-- ---------------------------------------------------------------------
CREATE TABLE profiles (
    id                  UUID PRIMARY KEY,
    user_id             UUID             NOT NULL,
    bio                 VARCHAR(500),
    job_title           VARCHAR(100),
    company             VARCHAR(100),
    school              VARCHAR(120),
    education_level     VARCHAR(60),
    hometown            VARCHAR(120),
    height_cm           INTEGER,
    religion            VARCHAR(60),
    politics            VARCHAR(60),
    zodiac_sign         VARCHAR(20),
    relationship_intent VARCHAR(40),
    drinking            VARCHAR(25),
    smoking             VARCHAR(25),
    cannabis            VARCHAR(25),
    exercise            VARCHAR(25),
    children            VARCHAR(40),
    completeness        DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ      NOT NULL,
    updated_at          TIMESTAMPTZ      NOT NULL,
    created_by          UUID,
    updated_by          UUID,
    version             BIGINT           NOT NULL DEFAULT 0,
    CONSTRAINT uk_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_profiles_height CHECK (height_cm IS NULL OR height_cm BETWEEN 120 AND 250)
);

CREATE TABLE profile_languages (
    profile_id UUID        NOT NULL,
    language   VARCHAR(40) NOT NULL,
    CONSTRAINT fk_profile_languages_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX idx_profile_languages_profile ON profile_languages (profile_id);

CREATE TABLE profile_interests (
    profile_id  UUID NOT NULL,
    interest_id UUID NOT NULL,
    PRIMARY KEY (profile_id, interest_id),
    CONSTRAINT fk_profile_interests_profile  FOREIGN KEY (profile_id)  REFERENCES profiles (id)  ON DELETE CASCADE,
    CONSTRAINT fk_profile_interests_interest FOREIGN KEY (interest_id) REFERENCES interests (id) ON DELETE CASCADE
);
CREATE INDEX idx_profile_interests_interest ON profile_interests (interest_id);

CREATE TABLE profile_qualities (
    profile_id UUID NOT NULL,
    quality_id UUID NOT NULL,
    PRIMARY KEY (profile_id, quality_id),
    CONSTRAINT fk_profile_qualities_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)  ON DELETE CASCADE,
    CONSTRAINT fk_profile_qualities_quality FOREIGN KEY (quality_id) REFERENCES qualities (id) ON DELETE CASCADE
);
CREATE INDEX idx_profile_qualities_quality ON profile_qualities (quality_id);

CREATE TABLE prompt_answers (
    id            UUID PRIMARY KEY,
    user_id       UUID         NOT NULL,
    prompt_id     UUID         NOT NULL,
    answer        VARCHAR(300) NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    UUID,
    updated_by    UUID,
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_prompt_answers_user_prompt UNIQUE (user_id, prompt_id),
    CONSTRAINT fk_prompt_answers_user   FOREIGN KEY (user_id)   REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_prompt_answers_prompt FOREIGN KEY (prompt_id) REFERENCES prompts (id) ON DELETE CASCADE
);
CREATE INDEX idx_prompt_answers_user ON prompt_answers (user_id);

CREATE TABLE photos (
    id                UUID PRIMARY KEY,
    user_id           UUID         NOT NULL,
    storage_key       VARCHAR(300) NOT NULL,
    url               VARCHAR(600) NOT NULL,
    blurhash          VARCHAR(64),
    width             INTEGER,
    height            INTEGER,
    caption           VARCHAR(140),
    display_order     INTEGER      NOT NULL DEFAULT 0,
    is_primary        BOOLEAN      NOT NULL DEFAULT FALSE,
    moderation_status VARCHAR(20)  NOT NULL DEFAULT 'APPROVED',
    comment_count     INTEGER      NOT NULL DEFAULT 0,
    like_count        INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        UUID,
    updated_by        UUID,
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_photos_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_photos_user       ON photos (user_id);
CREATE INDEX idx_photos_user_order ON photos (user_id, display_order);

-- ---------------------------------------------------------------------
-- Interaction: likes, passes, matches
-- ---------------------------------------------------------------------
CREATE TABLE likes (
    id                     UUID PRIMARY KEY,
    sender_id              UUID         NOT NULL,
    receiver_id            UUID         NOT NULL,
    type                   VARCHAR(20)  NOT NULL DEFAULT 'STANDARD',
    status                 VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    target_photo_id        UUID,
    target_prompt_answer_id UUID,
    note                   VARCHAR(200),
    seen                   BOOLEAN      NOT NULL DEFAULT FALSE,
    from_auto_match        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL,
    created_by             UUID,
    updated_by             UUID,
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_likes_pair UNIQUE (sender_id, receiver_id),
    CONSTRAINT ck_likes_not_self CHECK (sender_id <> receiver_id),
    CONSTRAINT fk_likes_sender   FOREIGN KEY (sender_id)   REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_likes_receiver_status ON likes (receiver_id, status);
CREATE INDEX idx_likes_sender_status   ON likes (sender_id, status);
CREATE INDEX idx_likes_created         ON likes (created_at);
-- Powers the standout popularity aggregate, which groups recent likes by receiver.
CREATE INDEX idx_likes_receiver_recent ON likes (receiver_id, created_at);

CREATE TABLE passes (
    id          UUID PRIMARY KEY,
    sender_id   UUID        NOT NULL,
    receiver_id UUID        NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    version     BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_passes_pair UNIQUE (sender_id, receiver_id),
    CONSTRAINT ck_passes_not_self CHECK (sender_id <> receiver_id),
    CONSTRAINT fk_passes_sender   FOREIGN KEY (sender_id)   REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_passes_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_passes_sender_expires ON passes (sender_id, expires_at);

-- user_a_id is always the smaller UUID of the pair. That canonical ordering is what
-- lets a single unique constraint enforce "one match per pair" under concurrency.
CREATE TABLE matches (
    id                  UUID PRIMARY KEY,
    user_a_id           UUID         NOT NULL,
    user_b_id           UUID         NOT NULL,
    source              VARCHAR(30)  NOT NULL DEFAULT 'MUTUAL_LIKE',
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    matched_at          TIMESTAMPTZ  NOT NULL,
    compatibility_score DOUBLE PRECISION,
    highlights          VARCHAR(400),
    conversation_id     UUID,
    unmatched_by        UUID,
    unmatched_at        TIMESTAMPTZ,
    last_interaction_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    created_by          UUID,
    updated_by          UUID,
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_matches_pair UNIQUE (user_a_id, user_b_id),
    CONSTRAINT ck_matches_ordering CHECK (user_a_id < user_b_id),
    CONSTRAINT fk_matches_user_a FOREIGN KEY (user_a_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_matches_user_b FOREIGN KEY (user_b_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_matches_user_a     ON matches (user_a_id, status);
CREATE INDEX idx_matches_user_b     ON matches (user_b_id, status);
CREATE INDEX idx_matches_matched_at ON matches (matched_at);

-- One row per user per cadence per period. The unique constraint is the idempotency
-- guard for the scheduler: retries and manual triggers converge instead of duplicating.
CREATE TABLE auto_match_runs (
    id                    UUID PRIMARY KEY,
    user_id               UUID        NOT NULL,
    cadence               VARCHAR(10) NOT NULL,
    period_key            VARCHAR(12) NOT NULL,
    outcome               VARCHAR(30) NOT NULL,
    matched_user_id       UUID,
    match_id              UUID,
    score                 DOUBLE PRECISION,
    candidates_considered INTEGER     NOT NULL DEFAULT 0,
    note                  VARCHAR(300),
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ NOT NULL,
    created_by            UUID,
    updated_by            UUID,
    version               BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_auto_match_runs_scope UNIQUE (user_id, cadence, period_key),
    CONSTRAINT fk_auto_match_runs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_auto_match_runs_period ON auto_match_runs (period_key);

-- ---------------------------------------------------------------------
-- Chat
-- ---------------------------------------------------------------------
CREATE TABLE conversations (
    id                     UUID PRIMARY KEY,
    match_id               UUID         NOT NULL,
    user_a_id              UUID         NOT NULL,
    user_b_id              UUID         NOT NULL,
    status                 VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    first_sender_id        UUID,
    both_spoke             BOOLEAN      NOT NULL DEFAULT FALSE,
    opener_message_count   INTEGER      NOT NULL DEFAULT 0,
    last_message_at        TIMESTAMPTZ,
    last_message_preview   VARCHAR(160),
    last_message_sender_id UUID,
    unread_for_user_a      INTEGER      NOT NULL DEFAULT 0,
    unread_for_user_b      INTEGER      NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL,
    created_by             UUID,
    updated_by             UUID,
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_conversations_match UNIQUE (match_id),
    CONSTRAINT fk_conversations_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE
);
CREATE INDEX idx_conversations_user_a ON conversations (user_a_id, last_message_at);
CREATE INDEX idx_conversations_user_b ON conversations (user_b_id, last_message_at);

ALTER TABLE matches
    ADD CONSTRAINT fk_matches_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE SET NULL;

CREATE TABLE messages (
    id                UUID PRIMARY KEY,
    conversation_id   UUID          NOT NULL,
    sender_id         UUID          NOT NULL,
    type              VARCHAR(20)   NOT NULL DEFAULT 'TEXT',
    body              VARCHAR(2000),
    reply_to_id       UUID,
    delivered_at      TIMESTAMPTZ,
    read_at           TIMESTAMPTZ,
    deleted           BOOLEAN       NOT NULL DEFAULT FALSE,
    client_message_id VARCHAR(64),
    created_at        TIMESTAMPTZ   NOT NULL,
    updated_at        TIMESTAMPTZ   NOT NULL,
    created_by        UUID,
    updated_by        UUID,
    version           BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender       FOREIGN KEY (sender_id)       REFERENCES users (id)         ON DELETE CASCADE
);
CREATE INDEX idx_messages_conversation_created ON messages (conversation_id, created_at DESC);
CREATE INDEX idx_messages_sender ON messages (sender_id);
-- Send de-duplication looks a message up by its client-generated id.
CREATE UNIQUE INDEX uk_messages_client_id ON messages (sender_id, client_message_id)
    WHERE client_message_id IS NOT NULL;

CREATE TABLE message_attachments (
    id               UUID PRIMARY KEY,
    message_id       UUID          NOT NULL,
    storage_key      VARCHAR(300)  NOT NULL,
    url              VARCHAR(600)  NOT NULL,
    content_type     VARCHAR(100)  NOT NULL,
    file_name        VARCHAR(200),
    size_bytes       BIGINT        NOT NULL,
    width            INTEGER,
    height           INTEGER,
    duration_seconds INTEGER,
    waveform         VARCHAR(1000),
    thumbnail_url    VARCHAR(600),
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL,
    created_by       UUID,
    updated_by       UUID,
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_message_attachments_message FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE
);
CREATE INDEX idx_message_attachments_message ON message_attachments (message_id);

CREATE TABLE call_sessions (
    id               UUID PRIMARY KEY,
    conversation_id  UUID        NOT NULL,
    caller_id        UUID        NOT NULL,
    callee_id        UUID        NOT NULL,
    type             VARCHAR(10) NOT NULL DEFAULT 'VOICE',
    status           VARCHAR(20) NOT NULL DEFAULT 'RINGING',
    started_at       TIMESTAMPTZ NOT NULL,
    answered_at      TIMESTAMPTZ,
    ended_at         TIMESTAMPTZ,
    duration_seconds INTEGER,
    end_reason       VARCHAR(40),
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    created_by       UUID,
    updated_by       UUID,
    version          BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_call_sessions_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE
);
CREATE INDEX idx_call_sessions_conversation ON call_sessions (conversation_id, created_at);
CREATE INDEX idx_call_sessions_status       ON call_sessions (status);

-- ---------------------------------------------------------------------
-- Photo comments
-- ---------------------------------------------------------------------
CREATE TABLE photo_comments (
    id                UUID PRIMARY KEY,
    photo_id          UUID         NOT NULL,
    photo_owner_id    UUID         NOT NULL,
    author_id         UUID         NOT NULL,
    body              VARCHAR(300) NOT NULL,
    parent_comment_id UUID,
    hidden            BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden_by         UUID,
    like_count        INTEGER      NOT NULL DEFAULT 0,
    reply_count       INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        UUID,
    updated_by        UUID,
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_photo_comments_not_self CHECK (author_id <> photo_owner_id),
    CONSTRAINT fk_photo_comments_photo  FOREIGN KEY (photo_id)          REFERENCES photos (id)         ON DELETE CASCADE,
    CONSTRAINT fk_photo_comments_author FOREIGN KEY (author_id)         REFERENCES users (id)          ON DELETE CASCADE,
    CONSTRAINT fk_photo_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES photo_comments (id) ON DELETE CASCADE
);
CREATE INDEX idx_photo_comments_photo  ON photo_comments (photo_id, created_at);
CREATE INDEX idx_photo_comments_owner  ON photo_comments (photo_owner_id, created_at);
CREATE INDEX idx_photo_comments_author ON photo_comments (author_id, created_at);

-- ---------------------------------------------------------------------
-- Safety
-- ---------------------------------------------------------------------
CREATE TABLE blocks (
    id         UUID PRIMARY KEY,
    blocker_id UUID         NOT NULL,
    blocked_id UUID         NOT NULL,
    reason     VARCHAR(200),
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    created_by UUID,
    updated_by UUID,
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_blocks_pair UNIQUE (blocker_id, blocked_id),
    CONSTRAINT ck_blocks_not_self CHECK (blocker_id <> blocked_id),
    CONSTRAINT fk_blocks_blocker FOREIGN KEY (blocker_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_blocks_blocked FOREIGN KEY (blocked_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_blocks_blocker ON blocks (blocker_id);
CREATE INDEX idx_blocks_blocked ON blocks (blocked_id);

CREATE TABLE reports (
    id               UUID PRIMARY KEY,
    reporter_id      UUID          NOT NULL,
    reported_user_id UUID          NOT NULL,
    reason           VARCHAR(40)   NOT NULL,
    details          VARCHAR(1000),
    context_type     VARCHAR(30),
    context_id       UUID,
    status           VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    moderator_note   VARCHAR(1000),
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL,
    created_by       UUID,
    updated_by       UUID,
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_reports_not_self CHECK (reporter_id <> reported_user_id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id)      REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_reported FOREIGN KEY (reported_user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_reports_reported ON reports (reported_user_id);
CREATE INDEX idx_reports_status   ON reports (status);

-- ---------------------------------------------------------------------
-- Plans, subscriptions, quotas
-- ---------------------------------------------------------------------
CREATE TABLE plans (
    id                    UUID PRIMARY KEY,
    code                  VARCHAR(40)  NOT NULL,
    name                  VARCHAR(80)  NOT NULL,
    description           VARCHAR(300),
    tier                  VARCHAR(20)  NOT NULL,
    price_minor           BIGINT       NOT NULL,
    currency              VARCHAR(3)   NOT NULL DEFAULT 'USD',
    billing_period_months INTEGER      NOT NULL DEFAULT 1,
    display_order         INTEGER      NOT NULL DEFAULT 0,
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL,
    created_by            UUID,
    updated_by            UUID,
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_plans_code UNIQUE (code)
);

CREATE TABLE subscriptions (
    id                 UUID PRIMARY KEY,
    user_id            UUID         NOT NULL,
    plan_id            UUID         NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    started_at         TIMESTAMPTZ  NOT NULL,
    current_period_end TIMESTAMPTZ  NOT NULL,
    cancelled_at       TIMESTAMPTZ,
    auto_renew         BOOLEAN      NOT NULL DEFAULT TRUE,
    provider           VARCHAR(30)  DEFAULT 'internal',
    provider_reference VARCHAR(120),
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,
    created_by         UUID,
    updated_by         UUID,
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans (id)
);
CREATE INDEX idx_subscriptions_user        ON subscriptions (user_id);
CREATE INDEX idx_subscriptions_user_status ON subscriptions (user_id, status);

-- One counter per (user, feature, period). Consumption is a conditional UPDATE against
-- this row, which is what makes "5 comments a day" safe under concurrent requests.
CREATE TABLE usage_counters (
    id         UUID PRIMARY KEY,
    user_id    UUID        NOT NULL,
    feature    VARCHAR(40) NOT NULL,
    period_key VARCHAR(12) NOT NULL,
    used       INTEGER     NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by UUID,
    updated_by UUID,
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_usage_counters_scope UNIQUE (user_id, feature, period_key),
    CONSTRAINT ck_usage_counters_used CHECK (used >= 0),
    CONSTRAINT fk_usage_counters_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_usage_counters_user ON usage_counters (user_id);

-- ---------------------------------------------------------------------
-- Media, notifications, standouts
-- ---------------------------------------------------------------------
CREATE TABLE media_assets (
    id               UUID PRIMARY KEY,
    owner_id         UUID          NOT NULL,
    storage_key      VARCHAR(300)  NOT NULL,
    url              VARCHAR(600)  NOT NULL,
    content_type     VARCHAR(100)  NOT NULL,
    file_name        VARCHAR(200),
    size_bytes       BIGINT        NOT NULL,
    width            INTEGER,
    height           INTEGER,
    duration_seconds INTEGER,
    waveform         VARCHAR(1000),
    purpose          VARCHAR(30)   NOT NULL,
    consumed         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL,
    created_by       UUID,
    updated_by       UUID,
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_media_assets_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_media_assets_owner    ON media_assets (owner_id);
CREATE INDEX idx_media_assets_consumed ON media_assets (consumed, created_at);

CREATE TABLE notifications (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL,
    type        VARCHAR(40)  NOT NULL,
    title       VARCHAR(120) NOT NULL,
    body        VARCHAR(300),
    actor_id    UUID,
    target_type VARCHAR(30),
    target_id   UUID,
    image_url   VARCHAR(600),
    read_flag   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_read    ON notifications (user_id, read_flag);

-- A whole ranking is written under a new cycle_key, then the previous cycle is dropped.
-- Readers therefore never observe a half-built shelf.
CREATE TABLE standout_snapshots (
    id             UUID PRIMARY KEY,
    cycle_key      VARCHAR(20)      NOT NULL,
    user_id        UUID             NOT NULL,
    city           VARCHAR(120),
    country        VARCHAR(2),
    score          DOUBLE PRECISION NOT NULL,
    rank_position  INTEGER          NOT NULL,
    reason         VARCHAR(30)      NOT NULL,
    likes_received INTEGER          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ      NOT NULL,
    updated_at     TIMESTAMPTZ      NOT NULL,
    created_by     UUID,
    updated_by     UUID,
    version        BIGINT           NOT NULL DEFAULT 0,
    CONSTRAINT uk_standout_snapshots_scope UNIQUE (cycle_key, user_id),
    CONSTRAINT fk_standout_snapshots_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_standout_snapshots_cycle ON standout_snapshots (cycle_key, rank_position);
CREATE INDEX idx_standout_snapshots_city  ON standout_snapshots (cycle_key, city);
